[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.53"
crossterm = "0.29.0"
framework = { version = "0.1.0", path = "../framework" }
ratatui = "0.29.0"
tui-textarea = "0.7.0"

[lints]
workspace = true

[dev-dependencies]
insta = "1.44.3"
